### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by abrambailey** [storyblok/quickstart-templates#1]
It would be nice if this quickstart template mapped onto something, like your demo app, so that the schema made sense from the Storyblok app side.

**Comment by DominikAngerer** [comment]
Hey there! The Quickstart Templates do map directly to the "Create a new space" option. 

The `home` content entry directly contains the content-type `page` and the nestable components:

- `teaser`
- `grid`
- `feature`

I'll update the readme on this so it will be easier to understand. If I'm not mistaken those examples are also available for download including a configuration in a fresh project.

![bildschirmfoto 2018-06-13 um 12 15 46](https://user-images.githubusercontent.com/7952803/41345308-8d65255e-6f03-11e8-874d-10a5f9eca357.jpg)

The Rendering Service Boostrap Demo app matches with the following repository:  https://github.com/storyblok/bootstrap-demo

Best,
Dominik

**Comment by DominikAngerer** [comment]
We've updated our onboarding view to allow exactly that.

https://www.storyblok.com/cl/updated-onboarding
